# Generated by Django 4.0.2 on 2023-04-24 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_recipe_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeManager',
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Recipe', 'verbose_name_plural': 'Recipes'},
        ),
    ]
